services:
  - type: web
    name: supermercado-suma
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install numpy Cython cmdstanpy --prefer-binary
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
